import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import AdminAccessLink from "@/components/AdminAccessLink";
import dynamic from "next/dynamic";

const FirebaseProviderSimple = dynamic(() => import("@/components/FirebaseProviderSimple"), {
  ssr: false,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Walmart 2.0 clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FirebaseProviderSimple>
          <Header />

          <div className="flex">
            {modal}
            {children}
          </div>
          
          <AdminAccessLink />
        </FirebaseProviderSimple>
      </body>
    </html>
  );
}
